output error message to stderr

diff --git a/afewmore b/afewmore
--- a/afewmore
+++ b/afewmore
@@ -7,7 +7,7 @@ log() {
 }
 
 exit_with_error() {
-    echo "ERROR:" $@
+    echo "ERROR:" $@ >&2
     exit 1
 }
 
